//
// Created by Adrian on 12/17/2025.
//

#ifndef MEAL_RECIPE_CALCULATEVALUEOFRECIPE_H
#define MEAL_RECIPE_CALCULATEVALUEOFRECIPE_H


class calculateValueOfRecipe
{
};


#endif //MEAL_RECIPE_CALCULATEVALUEOFRECIPE_H